# Generated by Django 5.0.3 on 2024-03-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawchatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chats',
        ),
    ]
