# Generated by Django 5.0.3 on 2024-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawchatbot', '0003_chats_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
