# Generated by Django 5.0.3 on 2024-04-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawchatbot', '0004_messages_dislike_messages_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
